services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bet-maker:
    build:
      context: ./bet_maker
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8001

  line-provider:
    build:
      context: ./line_provider
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data: